apiVersion: v1
kind: Service
metadata:
  name: landingpage
  labels:
    app.kubernetes.io/name: landingpage
spec:
  selector:
    app.kubernetes.io/name: landingpage
  ports:
    - protocol: TCP
      port: { { .Values.service.port } }
      targetPort: 3000
